apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    name: redis
  namespace: operations
spec:
  replicas: 1
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "0.1"
