apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
    role: service
  name: redis
  namespace: operations
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
  selector:
    name: redis
